Refactoring
Flash3388/Tracer pull request #98
Opened 2021-01-20 02:45 UTC by dandeduck

Mostly just an update to the new flashlib (mostly for pid controller changes)

2021-01-20 08:19 UTC, tomtzook requested changes
Just some small things really, mostly about _Gradle_.

I didn't try to build it since I'm not at home, so I'm trusting you. You might want to add CI in the future.

2021-01-20 08:19 UTC, tomtzook commented on src/main/java/tracer/actions/FollowerAction.java
> +        setConfiguration(new ActionConfiguration(getConfiguration().getRequirements(), followable.duration(), getConfiguration().getName(), getConfiguration().shouldRunWhenDisabled()));
Just call `withTimeout`.
Or: 
```java
configure().setTimeout(timeout);
```

2021-01-20 08:19 UTC, tomtzook commented on build.gradle
> +    compile "com.flash3388.flashlib:flashlib.core.scheduling:3.0.0-alpha.3"
Use `implementation`, or `api`.

https://docs.gradle.org/current/userguide/declaring_dependencies.html

2021-01-20 08:19 UTC, tomtzook commented on build.gradle
> +    id 'java'
Use the `java-library` plugin.

https://docs.gradle.org/current/userguide/java_library_plugin.html

2021-01-20 08:19 UTC, tomtzook commented on src/main/java/tracer/actions/FollowerAction.java
>          setValues(relativeTime());
You can use `getRunTime()` instead of `relativeTime`.
It will return the time that has passed since the action started running.

2021-01-20 08:19 UTC, tomtzook commented on build.gradle
> +    compile "com.flash3388.flashlib:flashlib.core.robot:3.0.0-alpha.3"
Do you actually need this? I haven't seen any usage relating to  `robot`.

2021-01-20 08:19 UTC, tomtzook commented on build.gradle
> +    compile "com.flash3388.util:jmath:1.0"
Switch to a newer version. It also has a different group:
https://mvnrepository.com/artifact/com.github.tomtzook/jmath

2021-01-20 08:19 UTC, tomtzook commented on build.gradle
>              url "https://plugins.gradle.org/m2/"
You can remove the `buildscript` block.

2021-01-20 08:19 UTC, tomtzook commented on build.gradle
> +allprojects {
You only have one project, you can just do
```groovy
version = VERSION_NAME
group = GROUP
```

2021-01-20 08:19 UTC, tomtzook commented on build.gradle
Add a `source`/`target` `compatibility` indication:
https://docs.gradle.org/current/userguide/building_java_projects.html#sec:java_cross_compilation

2021-01-20 19:11 UTC, dandeduck commented on src/main/java/tracer/actions/FollowerAction.java
> +        setConfiguration(new ActionConfiguration(getConfiguration().getRequirements(), followable.duration(), getConfiguration().getName(), getConfiguration().shouldRunWhenDisabled()));
btw `setTimeout`  is default scope, thus inaccessible

2021-01-20 19:12 UTC, dandeduck commented on src/main/java/tracer/actions/FollowerAction.java
>          setValues(relativeTime());
yeah, it's from the last flashlib

2021-01-20 19:14 UTC, dandeduck commented on build.gradle
> +    id 'java'
ok

2021-01-20 19:15 UTC, dandeduck commented on build.gradle
> +    compile "com.flash3388.flashlib:flashlib.core.scheduling:3.0.0-alpha.3"
Yeah, I accidentally copied it from somewhere

2021-01-20 19:16 UTC, dandeduck commented on build.gradle
> +    compile "com.flash3388.flashlib:flashlib.core.robot:3.0.0-alpha.3"
Yeah, for sure (I added them as I needed) `Drive` may be?

2021-01-20 19:17 UTC, dandeduck commented on build.gradle
> +    compile "com.flash3388.util:jmath:1.0"
There was a reason for using this version of jmath (a bug in a newer version that was in flashlib?) does it really matter?

2021-01-20 19:17 UTC, dandeduck commented on build.gradle
>              url "https://plugins.gradle.org/m2/"
k

2021-01-20 19:17 UTC, dandeduck commented on build.gradle
> +allprojects {
k

2021-01-20 19:24 UTC, dandeduck commented on build.gradle
Not sure I put the right versions tho, but 8 seems fine

2021-01-21 07:54 UTC, tomtzook commented on src/main/java/tracer/actions/FollowerAction.java
> +        setConfiguration(new ActionConfiguration(getConfiguration().getRequirements(), followable.duration(), getConfiguration().getName(), getConfiguration().shouldRunWhenDisabled()));
`ActionConfiguration.setTimeout` might be `default`, but not `ActionConfiguration.Editor.setTimeout`.

But nvm.

2021-01-21 07:56 UTC, tomtzook commented on build.gradle
> +    compile "com.flash3388.util:jmath:1.0"
It's always better to use the newer version. What bug? maybe it was fixed already?
I think it's best to switch and see if you encounter this bug. If so, we can fix _jmath_.

2021-01-21 07:57 UTC, tomtzook commented on build.gradle
Use the constants, i.e. `JavaVersion.VERSION_1_8` instead of a number. 

Didn't you want to use things from _JDK 11_?

2021-01-21 07:59 UTC, tomtzook reviewed
Still a bunch more. Also from previous one.

What about testing?

2021-01-21 07:59 UTC, tomtzook commented on src/main/java/tracer/actions/FollowerAction.java
> +        this.drive = drive;
Add `requires(drive)` as requirement declaration is not _required_ by actions in libraries.

2021-01-22 03:56 UTC, dandeduck commented on build.gradle
> +    compile "com.flash3388.util:jmath:1.0"
May be not a bug, may be some change, but whatever

2021-01-22 03:58 UTC, dandeduck commented on build.gradle
Yeah, how did it build?

2021-01-22 04:00 UTC, dandeduck commented on src/main/java/tracer/actions/FollowerAction.java
> +        this.drive = drive;
didn't know that it's a thing

2021-01-22 04:21 UTC, dandeduck commented
I added CI, regarding tests, there are tests for base functionality and object, I might add tests for  utils, but I don't really wanna add them for more complex objects since they mostly rely on the basic stuff that is tested. I know that it's better to retest things but ugh

2021-01-22 06:44 UTC, tomtzook commented on build.gradle
It doesn't specify which _JDK_ to use, but rather what _bytecode_ version.

2021-01-22 06:48 UTC, tomtzook approved these changes
Looks good. 

You can now modify the repository to require successful CI before allowing to merge pull requests. (pretty important).

Merge at your convenience.

2021-01-22 06:49 UTC, dandeduck commented
Already added CI requirements for dev and master pushes, please go ahead and merge, I'm not at the PC right now

2021-01-22 06:51 UTC, dandeduck commented
> Already added CI requirements for dev and master pushes, please go ahead and merge, I'm not at the PC right now

or I'll do it later myself, no biggie

2021-01-22 17:10 UTC, merged